version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./:/usr/src/client:rw,cached
      - /usr/src/client/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  proxy:
    container_name: proxy
    image: nginx:1.16.0-alpine
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.com
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    command: ["nginx", "-g", "daemon off;"]
