apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "react-image-compressor.fullname" . }}
  labels:
    {{- include "react-image-compressor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      {{- include "react-image-compressor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "react-image-compressor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "react-image-compressor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $path, $config := .Values.service.list }}
            - containerPort: {{ $config.targetPort }}
              protocol: {{ $config.protocol }}
              name: {{ $path }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.deployment.liveness | nindent 12 }}
          readinessProbe:
          {{- toYaml .Values.deployment.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: nginx-exporter
          image: {{ .Values.deployment.exporter.image }}
          ports:
            - containerPort: {{ .Values.deployment.exporter.containerPort }}
          resources:
            {{- toYaml .Values.deployment.exporter.resoureces | nindent 12 }}
          {{ with  .Values.deployment.exporter.command }}
          args: {{ .args }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
