{{- if eq .Values.podDisruptionBudget.enabled true}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "react-image-compressor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "react-image-compressor.labels" . | indent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable}}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "react-image-compressor.selectorLabels" . | nindent 6 }}
  {{- end }}
