apiVersion: v1
kind: Service
metadata:
  name: {{ include "react-image-compressor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "react-image-compressor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $path, $config := .Values.service.list }}
    - port: {{ $config.port }}
      targetPort: {{ $config.targetPort}}
      protocol: {{ $config.protocol }}
      name: {{ $path }}
  {{- end }}
  selector:
    {{- include "react-image-compressor.selectorLabels" . | nindent 4 }}
